### ISSUE TITLE
Back button animation should be reversed

### ISSUE THREAD

**Issue by ackermcc** [GoTally/DecisionModelPrototypeApp#7]
This also applies to any view that would go over a current view, such as the Deadline, Choices and People links.

**Comment by zoso10** [comment]
Alright the horizontal page animations should be correct. I think allowing for vertical page animations is going to require a lot more work and probably will need a rework. I don't think it warrants the time for the beta. Hopefully we can test this and get it merged soon :shipit:

**Comment by ackermcc** [comment]
Its not perfect, but its better. I think using the Osen UI to its full potential will alleviate these problems in the future...lets stick to the more functional bugs for the moment. What do you think?
